version: 0.0.7.{build}
configuration: Release
image: Visual Studio 2017
build:
  project: foo_input_spotify.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd %configuration%

    cp ..\libspotify\lib\libspotify.dll .

    7z a -tzip foo_input_spotify.fb2k-component *.dll

    7z a foo_input_spotify-pdb.7z *.pdb
artifacts:
- path: $(configuration)/foo_input_spotify.fb2k-component
  name: foo_input_spotify
- path: $(configuration)/foo_input_spotify-pdb.7z
  name: foo_input_spotify-pdb
deploy:
- provider: GitHub
  auth_token:
    secure: VysVOZvHypxy8qVnc4bCGlGk+xCkrriiiSmZ77uVSUQw8G8cvtdxJUAwH258NaRm1nPyoa5z4tWeRwJahqLYnKns1qJq/VO8DP0Jq6P3iI4=